datasets:
  moviecore_qa: # name of the dataset builder
    # data_dir: ${env.data_dir}/datasets
    data_type: videos # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: moviecore/annotation/moviecore_train.json
          storage: moviecore/annotation/moviecore_train.json
        val:
          url: moviecore/annotation/moviecore_test.json
          storage: moviecore/annotation/moviecore_test.json
        test:
          url: moviecore/annotation/moviecore_test.json
          storage: moviecore/annotation/moviecore_test.json
      videos:
        storage: moviecore/frames

      instance_id_key: question_id
